SELECT 
  COUNT(PERSOON_LBAID) AS AANTAL_ACTUELE_MELDINGEN
FROM COGDWPRD.DATAVIR_RO.T_LBA_PROCES_UGB_VW
WHERE 
  PROCES_PROCES IN ('Absoluut verzuim', 'Preventief', 'Relatief verzuim')
  AND (
    PROCES_STATUS NOT IN ('Melding gekoppeld', 'Niet behandeld')
    OR PROCES_STATUS IS NULL
  )
  AND PROCES_STARTDATUM_PLAN < DATE '2025-05-01'
  AND (
    PROCES_EINDDATUM_WERK IS NULL
    OR PROCES_EINDDATUM_WERK >= DATE '2025-05-01'
  );
