WITH 
VSV_PERCENTAGE_CBS AS (
  SELECT 
    ROUND(AVG(CAST(VoortijdigSchoolverlatersPercentage_4 AS FLOAT)), 1) AS Gemiddeld_VSV_Percentage
  FROM cbs.cbs.`84780NED/TypedDataSet`
  WHERE Regiokenmerken LIKE 'GM1883%'
    AND CAST(SUBSTR(Perioden, 1, 4) AS INT) BETWEEN 2018 AND 2022
),
SCHOOLLOOPBAAN_BASIS AS (
  SELECT  
    LBA.PERSOON_LBAID AS LEERLING_ID, 
    LBA.OPLEIDING_BEGINDATUM AS OPLEIDING_STARTDATUM,  
    LBA.OPLEIDING_CODE,  
    LBA.OPLEIDING_NIVEAU, 
    LBA.OPLEIDING_UITSTROOM, 
    SCHOOL.SCHOOL_NAAM, 
    SCHOOL.SCHOOL_SCHOOLSOORT, 
    SCHOOL.GEMEENTE_NAAM AS LOCATIE_PLAATS
  FROM COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW LBA
  LEFT JOIN COGDWPRD.DATAVIR_RO.T_LBA_SCHOOL_VW SCHOOL
    ON LBA.SCHOOL_BRIN = SCHOOL.SCHOOL_BRIN
),
TRAJECTEN AS (
  SELECT PERSOON_LBAID AS LEERLING_ID FROM COGDWPRD.DATAVIR_RO.T_LBA_TRAJECT_VW
),
MELDINGEN AS (
  SELECT PERSOON_LBAID AS LEERLING_ID FROM COGDWPRD.DATAVIR_RO.T_LBA_MELDING_VW
),
VERZUIM AS (
  SELECT PERSOON_LBAID AS LEERLING_ID
  FROM COGDWPRD.DATAVIR_RO.T_LBA_PROCES_UGB_VW
  WHERE 
    PROCES_PROCES IN ('Absoluut verzuim', 'Preventief', 'Relatief verzuim')
    AND (
      PROCES_STATUS NOT IN ('Melding gekoppeld', 'Niet behandeld')
      OR PROCES_STATUS IS NULL
    )
),
VRIJSTELLINGEN AS (
  SELECT PERSOON_LBAID AS LEERLING_ID FROM COGDWPRD.DATAVIR_RO.T_LBA_VRIJSTELLING_VW
)

SELECT 
  B.SCHOOL_NAAM,
  B.LOCATIE_PLAATS,
  COUNT(DISTINCT B.LEERLING_ID) AS AANTAL_ACTIEVE_LEERLINGEN,
  COUNT(DISTINCT T.LEERLING_ID) AS AANTAL_TRAJECTEN,
  COUNT(DISTINCT M.LEERLING_ID) AS AANTAL_MELDINGEN,
  COUNT(DISTINCT V.LEERLING_ID) AS AANTAL_VERZUIM,
  COUNT(DISTINCT VR.LEERLING_ID) AS AANTAL_VRIJSTELLINGEN,
  ROUND(
    COUNT(DISTINCT B.LEERLING_ID) * (
      SELECT COALESCE(Gemiddeld_VSV_Percentage, 0) / 100.0 FROM VSV_PERCENTAGE_CBS
    ), 0
  ) AS GESCHAT_AANTAL_VSV
FROM SCHOOLLOOPBAAN_BASIS B
LEFT JOIN TRAJECTEN T ON B.LEERLING_ID = T.LEERLING_ID
LEFT JOIN MELDINGEN M ON B.LEERLING_ID = M.LEERLING_ID
LEFT JOIN VERZUIM V ON B.LEERLING_ID = V.LEERLING_ID
LEFT JOIN VRIJSTELLINGEN VR ON B.LEERLING_ID = VR.LEERLING_ID
WHERE B.OPLEIDING_UITSTROOM IS NULL
  AND EXTRACT(YEAR FROM B.OPLEIDING_STARTDATUM) = 2023
  AND B.LOCATIE_PLAATS = 'Sittard-Geleen'
GROUP BY B.SCHOOL_NAAM, B.LOCATIE_PLAATS
ORDER BY GESCHAT_AANTAL_VSV DESC
LIMIT 20;
