
SELECT 
  OPLEIDING_UITSTROOM AS UITSTROOMREDEN,
  SCHOOL_SCHOOLSOORT,
  COUNT(DISTINCT LEERLING_ID) AS AANTAL_UITGESCHREVEN
FROM SCHOOLLOOPBAAN_BASIS
WHERE OPLEIDING_UITSTROOM IS NOT NULL
GROUP BY OPLEIDING_UITSTROOM, SCHOOL_SCHOOLSOORT
ORDER BY SCHOOL_SCHOOLSOORT, OPLEIDING_UITSTROOM;
