WITH MELDINGEN_MET_SCHOOL AS (
  SELECT 
    UGB.PERSOON_LBAID,
    UGB.PROCES_PROCES AS VERZUIM_TYPE,
    SCH.SCHOOL_NAAM,
    SCH.SCHOOL_SCHOOLSOORT
  FROM COGDWPRD.DATAVIR_RO.T_LBA_PROCES_UGB_VW UGB
  LEFT JOIN COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW LBA
    ON UGB.PERSOON_LBAID = LBA.PERSOON_LBAID
  LEFT JOIN COGDWPRD.DATAVIR_RO.T_LBA_SCHOOL_VW SCH
    ON LBA.SCHOOL_BRIN = SCH.SCHOOL_BRIN
  WHERE 
    UGB.PROCES_PROCES IN ('Absoluut verzuim', 'Preventief', 'Relatief verzuim')
    AND (
      UGB.PROCES_STATUS NOT IN ('Melding gekoppeld', 'Niet behandeld')
      OR UGB.PROCES_STATUS IS NULL
    )
    AND UGB.PROCES_STARTDATUM_PLAN >= DATE '2023-08-01'
    AND UGB.PROCES_STARTDATUM_PLAN <= DATE '2024-07-31'
)

SELECT 
  SCHOOL_SCHOOLSOORT AS ONDERWIJSSOORT,
  SCHOOL_NAAM AS ONDERWIJSINSTELLING,
  SUM(CASE WHEN VERZUIM_TYPE = 'Absoluut verzuim' THEN 1 ELSE 0 END) AS TOTAAL_ABSOLUUT,
  SUM(CASE WHEN VERZUIM_TYPE = 'Preventief' THEN 1 ELSE 0 END) AS TOTAAL_PREVENTIEF,
  SUM(CASE WHEN VERZUIM_TYPE = 'Relatief verzuim' THEN 1 ELSE 0 END) AS TOTAAL_RELATIEF,
  COUNT(*) AS TOTAAL_MELDINGEN
FROM MELDINGEN_MET_SCHOOL
GROUP BY 
  SCHOOL_SCHOOLSOORT,
  SCHOOL_NAAM
ORDER BY 
  SCHOOL_SCHOOLSOORT,
  SCHOOL_NAAM;
