
SELECT 
  B.SCHOOL_NAAM,
  B.LOCATIE_PLAATS,
  COUNT(DISTINCT B.LEERLING_ID) AS AANTAL_ACTIEVE_LEERLINGEN,
  COUNT(DISTINCT T.LEERLING_ID) AS AANTAL_TRAJECTEN,
  COUNT(DISTINCT M.LEERLING_ID) AS AANTAL_MELDINGEN,
  COUNT(DISTINCT V.LEERLING_ID) AS AANTAL_VERZUIM,
  COUNT(DISTINCT VR.LEERLING_ID) AS AANTAL_VRIJSTELLINGEN
FROM SCHOOLLOOPBAAN_BASIS B
LEFT JOIN TRAJECTEN T ON B.LEERLING_ID = T.LEERLING_ID
LEFT JOIN MELDINGEN M ON B.LEERLING_ID = M.LEERLING_ID
LEFT JOIN VERZUIM V ON B.LEERLING_ID = V.LEERLING_ID
LEFT JOIN VRIJSTELLINGEN VR ON B.LEERLING_ID = VR.LEERLING_ID
WHERE B.OPLEIDING_UITSTROOM IS NULL
  AND EXTRACT(YEAR FROM B.OPLEIDING_STARTDATUM) = 2023
GROUP BY B.SCHOOL_NAAM, B.LOCATIE_PLAATS
ORDER BY AANTAL_ACTIEVE_LEERLINGEN DESC
LIMIT 20;
