SELECT 
  COUNT(*) AS AANTAL_PREVENTIEF_VERZUIM_MELDINGEN
FROM COGDWPRD.DATAVIR_RO.T_LBA_PROCES_UGB_VW
WHERE 
  PROCES_PROCES = 'Preventief'
  AND (
    PROCES_STATUS NOT IN ('Melding gekoppeld', 'Niet behandeld')
    OR PROCES_STATUS IS NULL
  )
  AND PROCES_STARTDATUM_PLAN >= DATE '2023-08-01'
  AND PROCES_STARTDATUM_PLAN <= DATE '2024-07-31';
