
WITH SCHOOLLOOPBAAN_BASIS AS (
  SELECT  
    LBA.PERSOON_LBAID AS LEERLING_ID, 
    LBA.OPLEIDING_BEGINDATUM AS OPLEIDING_STARTDATUM,  
    LBA.OPLEIDING_CODE,  
    LBA.OPLEIDING_NIVEAU, 
    LBA.OPLEIDING_UITSTROOM, 
    SCHOOL.SCHOOL_NAAM, 
    SCHOOL.SCHOOL_SCHOOLSOORT, 
    SCHOOL.GEMEENTE_NAAM AS LOCATIE_PLAATS
  FROM COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW LBA
  LEFT JOIN COGDWPRD.DATAVIR_RO.T_LBA_SCHOOL_VW SCHOOL
    ON LBA.SCHOOL_BRIN = SCHOOL.SCHOOL_BRIN
),
TRAJECTEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    TRAJECT_BEGINDATUM,
    TRAJECT_EINDDATUM,
    TRAJECT_SOORT_CODE,
    TRAJECTSTATUS_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_TRAJECT_VW
),
MELDINGEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    MELDING_DATUM,
    MELDING_REDEN_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_MELDING_VW
),
VERZUIM AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    VERZUIM_BEGINDATUM,
    VERZUIM_EINDDATUM,
    VERZUIM_UREN,
    VERZUIMSOORT_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_VERZUIM_VW
),
VRIJSTELLINGEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    VRIJSTELLING_BEGINDATUM,
    VRIJSTELLING_EINDDATUM,
    VRIJSTELLINGREDEN_CODE,
    VRIJSTELLINGSOORT_TYPE,
    VRIJSTELLING_SCHOOLJAAR
  FROM COGDWPRD.DATAVIR_RO.T_LBA_VRIJSTELLING_VW
)

