
SELECT 
  EXTRACT(YEAR FROM TRAJECT_BEGINDATUM) AS jaar,
  EXTRACT(MONTH FROM TRAJECT_BEGINDATUM) AS maand,
  COUNT(*) AS trajecten_gestart
FROM COGDWPRD.DATAVIR_RO.T_LBA_TRAJECT_VW
WHERE TRAJECT_BEGINDATUM IS NOT NULL
GROUP BY 
  EXTRACT(YEAR FROM TRAJECT_BEGINDATUM),
  EXTRACT(MONTH FROM TRAJECT_BEGINDATUM)
ORDER BY jaar, maand;
