
SELECT 
  SB.SCHOOL_NAAM,
  EXTRACT(YEAR FROM VZ.VERZUIM_BEGINDATUM) AS SCHOOLJAAR,
  COUNT(*) AS AANTAL_VERZUIMGEVALLEN
FROM VERZUIM VZ
JOIN SCHOOLLOOPBAAN_BASIS SB
ON VZ.LEERLING_ID = SB.LEERLING_ID
WHERE VZ.VERZUIM_BEGINDATUM > DATE '2022-12-31'
GROUP BY SB.SCHOOL_NAAM, EXTRACT(YEAR FROM VZ.VERZUIM_BEGINDATUM)
ORDER BY SCHOOLJAAR, AANTAL_VERZUIMGEVALLEN DESC;
