
SELECT 
  EXTRACT(YEAR FROM VERZUIM_BEGINDATUM) AS jaar,
  COUNT(*) AS aantal_verzuimmomenten
FROM VERZUIM
WHERE VERZUIM_BEGINDATUM IS NOT NULL
GROUP BY EXTRACT(YEAR FROM VERZUIM_BEGINDATUM)
ORDER BY jaar;
