WITH 
SCHOOLLOOPBAAN_BASIS AS (
  SELECT  
    LBA.PERSOON_LBAID AS LEERLING_ID, 
    LBA.OPLEIDING_BEGINDATUM AS OPLEIDING_STARTDATUM,  
    LBA.OPLEIDING_CODE,  
    LBA.OPLEIDING_NIVEAU, 
    LBA.OPLEIDING_UITSTROOM, 
    SCHOOL.SCHOOL_NAAM, 
    SCHOOL.SCHOOL_SCHOOLSOORT, 
    SCHOOL.GEMEENTE_NAAM AS LOCATIE_PLAATS
  FROM COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW LBA
  LEFT JOIN COGDWPRD.DATAVIR_RO.T_LBA_SCHOOL_VW SCHOOL
    ON LBA.SCHOOL_BRIN = SCHOOL.SCHOOL_BRIN
),
TRAJECTEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    TRAJECT_BEGINDATUM,
    TRAJECT_EINDDATUM,
    TRAJECT_SOORT_CODE,
    TRAJECTSTATUS_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_TRAJECT_VW
),
MELDINGEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    MELDING_DATUM,
    MELDING_REDEN_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_MELDING_VW
),
VERZUIM AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    PROCES_STARTDATUM_PLAN AS VERZUIM_BEGINDATUM,
    PROCES_EINDDATUM_WERK AS VERZUIM_EINDDATUM,
    NULL AS VERZUIM_UREN,
    PROCES_PROCES AS VERZUIMSOORT_CODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_PROCES_UGB_VW
  WHERE 
    PROCES_PROCES IN ('Absoluut verzuim', 'Preventief', 'Relatief verzuim')
    AND (
      PROCES_STATUS NOT IN ('Melding gekoppeld', 'Niet behandeld')
      OR PROCES_STATUS IS NULL
    )
),
VRIJSTELLINGEN AS (
  SELECT
    PERSOON_LBAID AS LEERLING_ID,
    VRIJSTELLING_BEGINDATUM,
    VRIJSTELLING_EINDDATUM,
    VRIJSTELLINGREDEN_CODE,
    VRIJSTELLINGSOORT_TYPE,
    VRIJSTELLING_SCHOOLJAAR
  FROM COGDWPRD.DATAVIR_RO.T_LBA_VRIJSTELLING_VW
),
UITSCHRIJVING AS (
  SELECT 
    PERSOON_LBAID AS LEERLING_ID,
    MAX(OPLEIDING_EINDDATUM) AS LAATSTE_INSCHRIJVING,
    MAX(OPLEIDING_NIVEAU) AS LAATST_OPLEIDING_NIVEAU,
    MAX(OPLEIDING_UITSTROOM) AS UITSTROOMCODE
  FROM COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW
  GROUP BY PERSOON_LBAID
),
laatste_inschrijving AS (
  SELECT 
    PERSOON_LBAID,
    MAX(OPLEIDING_EINDDATUM) AS laatste_inschrijving,
    MAX(OPLEIDING_NIVEAU) AS laatst_opleiding_niveau,
    MAX(OPLEIDING_UITSTROOM) AS uitstroomcode
  FROM COGDWPRD.DATAVIR_RO.T_LBA_SCHOOLLOOPBAAN_VW
  GROUP BY PERSOON_LBAID
),
verzuim_signaal AS (
  SELECT 
    PERSOON_LBAID,
    COUNT(*) AS verzuimmomenten
  FROM COGDWPRD.DATAVIR_RO.T_LBA_VERZUIM_VW
  GROUP BY PERSOON_LBAID
),
melding_signaal AS (
  SELECT 
    PERSOON_LBAID,
    COUNT(*) AS meldingen
  FROM COGDWPRD.DATAVIR_RO.T_LBA_MELDING_VW
  GROUP BY PERSOON_LBAID
)
